package org.wikimedia.commons.donvip.spacemedia.repo.eso;

public enum EsoMetadata {
    WIDTH, HEIGHT, MEDIA_TYPE, FIELD_OF_VIEW, RELATED_ANNOUNCEMENT, RELATED_RELEASE, NAME, DISTANCE, ORIENTATION, CONSTELLATION, POSITION_RA, POSITION_DEC, TELESCOPE, TYPE, CATEGORY
}
