#/bin/sh
# Environment and secrets

# WIKIMEDIA INFRA

export MEM="9800m"
export SENTRY_DSN=
export OAUTH2_WIKIMEDIA_CLIENT_ID=
export OAUTH2_WIKIMEDIA_CLIENT_SECRET=
export user=
export password=
export hashes_user=
export hashes_password=
export TROVE_INSTANCE=
export COMMONS_API_PASSWORD=
export COMMONS_API_OAUTH1_CONSUMER_TOKEN=
export COMMONS_API_OAUTH1_CONSUMER_SECRET=
export COMMONS_API_OAUTH1_ACCESS_TOKEN=
export COMMONS_API_OAUTH1_ACCESS_SECRET=

# BOX

export BOX_API_OAUTH2_CLIENT_ID=
export BOX_API_OAUTH2_CLIENT_SECRET=
export BOX_API_USER_EMAIL=
export BOX_API_USER_PASSWORD=

# FLICKR

export FLICKR_API_KEY=
export FLICKR_SECRET=

# DVIDS

export DVIDS_API_KEY=

# YOUTUBE

export YOUTUBE_API_KEY=

# GOOGLE TRANSLATE

export GOOGLE_TRANSLATE_PROJECT=
export GOOGLE_TRANSLATE_PRIVATE_KEY_ID=
export GOOGLE_TRANSLATE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\\\n fill your private key here, in a single line \\\n-----END PRIVATE KEY-----\\\n"
export GOOGLE_TRANSLATE_CLIENT_EMAIL=
export GOOGLE_TRANSLATE_CLIENT_ID=

# MASTODON

export MASTODON_API_OAUTH2_ACCESS_TOKEN=
export MASTODON_API_OAUTH2_CLIENT_ID=
export MASTODON_API_OAUTH2_CLIENT_SECRET=

